version: '2'
services:
  api:
    build:
        context: .
        dockerfile: Dockerfile
    image: yiisoftware/yii2-php:7.1-apache
    container_name: yii2-apishop
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    networks:
      - apishopnet
    
  db:
    build:
      context: .
      dockerfile: DockerfileMySQL
    image: mysql:8
    ports:
      - "3306:3306"
    restart: always
    command: ["mysqld", "--mysql-native-password=ON"]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - apishopnet

networks:
  apishopnet:

